### ISSUE TITLE
Product Block Type & Containers

### ISSUE THREAD

**Issue by barnebys** [bitbag-commerce/CmsPlugin#23]
Hey guys, thanks for a nice plugin. 

We will use it for an upcoming product but we need to extend the bundle a bit. And I want to see if it is of interest of your's and on the roadmap before considering doing a PR.

1. Product Block Type  - We already extended our fork with a new block type adding linked products (just as a Page) since we need to control products within a block. 

2. Containers - Next step will be to add containers to configure a layout that consist 1 or more blocks since this is not supported in a page. That would allow users to have more freedom to create more complex containers to be rendered in a twig. 

Let me know your thoughts about it, and if it is any value for your project we would gladly contribute.

**Comment by bitbager** [comment]
1. I would suggest adding the products to block entity to make it more flexible. This will allow creating each block type with associated products. 

2. You mean allowing to write a filter within the content? Let's assume the user wants to add {{ `bitbag_render_block([code])` within the block and display it on the store front? I think this is a great idea and I had it in my mind.

As long as you will keep the coding standards we follow (basically the Sylius ones) and support strict PHP types I can accept your PR 🙂 .

**Comment by barnebys** [comment]
1. True, would just be a bit more clear to have it as an own type but yes it would be more flexible.
2. Yes something like that where the user can select a layout e.g. 2 columns and add rows, add a block into each column. Then it would have a routing just as Pages (maybe add support for different types for the Page entity?).

Sounds great, we will do some more work and handle the BDD, strict and code standards and then do a PR when we're done. :)

**Comment by bitbager** [comment]
Great! It's nice to see that more and more people are enjoying our work 🎉
