### ISSUE TITLE
Page in admin has no title

### ISSUE THREAD

**Issue by bitbager** [bitbag-commerce/CmsPlugin#40]
In the admin panel, when we go to the pages page, which btw sounds so weird, we don't have the nice "Pages" title 🙁

**Comment by kochen** [comment]
@bitbager are you reffering to this?
![image](https://user-images.githubusercontent.com/106042/32223613-56ea2aa4-be3e-11e7-96a0-2a884051b3c8.png)

**Comment by bitbager** [comment]
No, the page title is `| Pages` instead of `Sylius | Pages`. Actually is already fixed on dev branch. We can close it.

**Comment by kochen** [comment]
@bitbager not sure why you closed this, but the title should actually be:
```
{% block title %}{{ parent() }} {{ header|trans }}{% endblock %}
```

Shall I create a PR?

**Comment by bitbager** [comment]
Fixed on dev branch 🙂 
https://github.com/bitbag-commerce/CmsPlugin/blob/dev/src/Resources/views/Page/index.html.twig
